
# Hardcoded sample grocery data
from datetime import datetime, timedelta
import pandas as pd

data = [
    {"Food": "Milk", "Store": "SuperMart", "Location": "2323 S Leavitt St", "Original Price": 3.50, "Final Price": 2.89, "Expiration Date": (datetime.today().date() + timedelta(days=2)).strftime('%Y-%m-%d'), "Availability": "Available", "Click Count": 2},
    {"Food": "Bread", "Store": "FreshCo", "Location": "1400 W Monroe St", "Original Price": 2.00, "Final Price": 1.29, "Expiration Date": (datetime.today().date() + timedelta(days=1)).strftime('%Y-%m-%d'), "Availability": "Available", "Click Count": 4},
    {"Food": "Chicken Breast", "Store": "ValueFoods", "Location": "110 E Lockwood Ave", "Original Price": 8.00, "Final Price": 5.99, "Expiration Date": (datetime.today().date() + timedelta(days=3)).strftime('%Y-%m-%d'), "Availability": "Available", "Click Count": 1},
    {"Food": "Bananas", "Store": "GreenGrocers", "Location": "2857 S Kedvale Ave", "Original Price": 1.50, "Final Price": 1.29, "Expiration Date": (datetime.today().date() + timedelta(days=5)).strftime('%Y-%m-%d'), "Availability": "Available", "Click Count": 0},
    {"Food": "Yogurt", "Store": "MegaMarket", "Location": "2430 S St Louis Ave", "Original Price": 4.00, "Final Price": 3.29, "Expiration Date": (datetime.today().date() + timedelta(days=2)).strftime('%Y-%m-%d'), "Availability": "Sold Out", "Click Count": 6},
    {"Food": "Milk", "Store": "MegaMarket", "Location": "2430 S St Louis Ave", "Original Price": 2.94, "Final Price": 1.91, "Expiration Date": (datetime.today().date() + timedelta(days=6)).strftime('%Y-%m-%d'), "Availability": "Available", "Click Count": 3},
    {"Food": "Milk", "Store": "GreenGrocers", "Location": "2857 S Kedvale Ave", "Original Price": 2.46, "Final Price": 1.99, "Expiration Date": (datetime.today().date() + timedelta(days=12)).strftime('%Y-%m-%d'), "Availability": "Available", "Click Count": 3},
    {"Food": "Bananas", "Store": "SuperMart", "Location": "2323 S Leavitt St", "Original Price": 2.97, "Final Price": 2.32, "Expiration Date": (datetime.today().date() + timedelta(days=15)).strftime('%Y-%m-%d'), "Availability": "Available", "Click Count": 5},
    {"Food": "bread", "Store": "SuperMart", "Location": "2300 S 58th Ct", "Original Price": 1.60, "Final Price": 1.29, "Expiration Date": (datetime.today().date() + timedelta(days=7)).strftime('%Y-%m-%d'), "Availability": "Available", "Click Count": 2},
    {"Food": "Apples", "Store": "ValueFoods", "Location": "15 S Wood St", "Original Price": 2.90, "Final Price": 2.30, "Expiration Date": (datetime.today().date() + timedelta(days=10)).strftime('%Y-%m-%d'), "Availability": "Available", "Click Count": 4},
    {"Food": "Chicken Breast", "Store": "CityGrocer", "Location": "702 S Morgan St", "Original Price": 7.90, "Final Price": 6.29, "Expiration Date": (datetime.today().date() + timedelta(days=3)).strftime('%Y-%m-%d'), "Availability": "Available", "Click Count": 6},
    {"Food": "Milk", "Store": "CityGrocer", "Location": "702 S Morgan St", "Original Price": 2.99, "Final Price": 2.00, "Expiration Date": (datetime.today().date() + timedelta(days=2)).strftime('%Y-%m-%d'), "Availability": "Available", "Click Count": 1},
    {"Food": "Bread", "Store": "FarmBasket", "Location": "1717 S Morgan St", "Original Price": 2.20, "Final Price": 1.50, "Expiration Date": (datetime.today().date() + timedelta(days=2)).strftime('%Y-%m-%d'), "Availability": "Available", "Click Count": 4},
    {"Food": "Yogurt", "Store": "FarmBasket", "Location": "1717 S Morgan St", "Original Price": 3.90, "Final Price": 2.79, "Expiration Date": (datetime.today().date() + timedelta(days=5)).strftime('%Y-%m-%d'), "Availability": "Sold Out", "Click Count": 2},
    {"Food": "Cheese", "Store": "FarmBasket", "Location": "1315 W 32nd Pl", "Original Price": 5.10, "Final Price": 3.99, "Expiration Date": (datetime.today().date() + timedelta(days=4)).strftime('%Y-%m-%d'), "Availability": "Available", "Click Count": 4},
    {"Food": "Apples", "Store": "PureMart", "Location": "1917 S Michigan Ave", "Original Price": 3.00, "Final Price": 2.19, "Expiration Date": (datetime.today().date() + timedelta(days=7)).strftime('%Y-%m-%d'), "Availability": "Available", "Click Count": 5},
    {"Food": "Eggs", "Store": "PureMart", "Location": "300 W Van Buren St", "Original Price": 2.60, "Final Price": 2.49, "Expiration Date": (datetime.today().date() + timedelta(days=1)).strftime('%Y-%m-%d'), "Availability": "Available", "Click Count": 3},
    {"Food": "Carrots", "Store": "PureMart", "Location": "300 W Van Buren St", "Original Price": 1.50, "Final Price": 1.29, "Expiration Date": (datetime.today().date() + timedelta(days=8)).strftime('%Y-%m-%d'), "Availability": "Available", "Click Count": 1},
    {"Food": "Milk", "Store": "EcoFoods", "Location": "4100 W Jackson Blvd", "Original Price": 3.10, "Final Price": 2.29, "Expiration Date": (datetime.today().date() + timedelta(days=4)).strftime('%Y-%m-%d'), "Availability": "Available", "Click Count": 3},
    {"Food": "Eggs", "Store": "EcoFoods", "Location": "4100 W Jackson Blvd", "Original Price": 2.70, "Final Price": 1.99, "Expiration Date": (datetime.today().date() + timedelta(days=3)).strftime('%Y-%m-%d'), "Availability": "Available", "Click Count": 2},
    {"Food": "Bananas", "Store": "EcoFoods", "Location": "4100 W Jackson Blvd", "Original Price": 1.60, "Final Price": 1.29, "Expiration Date": (datetime.today().date() + timedelta(days=6)).strftime('%Y-%m-%d'), "Availability": "Available", "Click Count": 6},
    {"Food": "Apples", "Store": "UrbanHarvest", "Location": "4525 W Madison St", "Original Price": 1.50, "Final Price": .99, "Expiration Date": (datetime.today().date() + timedelta(days=5)).strftime('%Y-%m-%d'), "Availability": "Available", "Click Count": 3},
    {"Food": "Butter", "Store": "UrbanHarvest", "Location": "560 N Leclaire Ave", "Original Price": 2.50, "Final Price": 1.99, "Expiration Date": (datetime.today().date() + timedelta(days=3)).strftime('%Y-%m-%d'), "Availability": "Sold Out", "Click Count": 4},
    {"Food": "Bananas", "Store": "UrbanHarvest", "Location": "560 N Leclaire Ave", "Original Price": 2.90, "Final Price": 2.19, "Expiration Date": (datetime.today().date() + timedelta(days=9)).strftime('%Y-%m-%d'), "Availability": "Available", "Click Count": 2},
    {"Food": "Bread", "Store": "UrbanHarvest", "Location": "5629 W Fillmore St", "Original Price": 3.80, "Final Price": 2.99, "Expiration Date": (datetime.today().date() + timedelta(days=10)).strftime('%Y-%m-%d'), "Availability": "Available", "Click Count": 10}
]

grocery_df = pd.DataFrame(data) 